service: sopt-push-notification

frameworkVersion: '3'

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2
  environment:
    DYNAMODB_TABLE: ${env:DYNAMODB_TABLE}
    APN_TYPE: ${env:APN_TYPE}
    APN_NAME: ${env:APN_NAME}
    FCM_TYPE: ${env:FCM_TYPE}
    FCM_NAME: ${env:FCM_NAME}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: 'arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}'
        - Effect: Allow
          Action:
            - sns:Subscribe
            - sns:Unsubscribe
            - sns:Publish
          Resource:
            - 'arn:aws:sns:${opt:region, self:provider.region}:*:app/${self:provider.environment.APN_TYPE}/${self:provider.environment.APN_NAME}'
            - 'arn:aws:sns:${opt:region, self:provider.region}:*:app/${self:provider.environment.FCM_TYPE}/${self:provider.environment.FCM_NAME}'

custom:
  serverless-offline:
    httpPort: 4000

functions:
  service:
    handler: src/lambda.service
    events:
      - http:
          path: ''
          method: post
          cors: true
